--- 
- name: Baseline TACACS+ servers
  hosts: junosdevices
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no
  #strategy: debug
  vars_files:
   - group_vars/secrets.yml

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Build TACACS+ configlet
    template: 
       src: templates/tacplus.conf.j2
       dest: configs/{{ inventory_hostname }}_tacplus.conf

  - name: Load Replace TACPLUS Configlet
    junos_install_config: 
      host={{ inventory_hostname }}
      user={{ juniper_user }}
      passwd={{ juniper_passwd }}
      file=configs/{{ inventory_hostname }}_tacplus.conf
      comment="Ansible TACACS+ baseline"
      overwrite=false
      replace=true
      logfile=./config.log
      #update=replace  for newer versions

