--- 
- name: Baseline Root Password
  hosts: junosdevices
  roles:
   - Juniper.junos
  connection: local
  gather_facts: no
  strategy: debug
  vars_files:
   - group_vars/secrets.yml

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Build Root Password configlet
    template: 
       src: templates/root_password.conf.j2
       dest: configs/{{ inventory_hostname }}_root_password.conf

  - name: Load Root Password Configlet
    junos_install_config: 
      host={{ inventory_hostname }}
      user={{ juniper_user }}
      passwd={{ juniper_passwd }}
      file=configs/{{ inventory_hostname }}_root_password.conf
      comment="Ansible set root password"
      overwrite=false
      replace=true
      logfile=./config.log
      #update=replace  for newer versions
      
  - name: Delete configlet (contains sensitive data)
    file:
        path: configs/{{ inventory_hostname }}_root_password.conf
        state: absent
