--- 
- name: Push Configlet
  hosts: junosdevices
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Push a Configlet and merge it
    junos_install_config: 
      host={{ inventory_hostname }}
      user={{ juniper_user }}
      passwd={{ juniper_passwd }}
      file={{ configlet }}
      overwrite=false
      logfile=./config.log
